option("build-tests")
    set_default(true)
    set_showmenu(true)
    set_description("Build local validation targets")
option_end()

option("merge-weak-object")
    set_default(true)
    set_showmenu(true)
    set_description("Merge weak-symbol object files into one relocatable object when the platform supports it")
option_end()

option("stdlib")
    set_default("default")
    set_showmenu(true)
    set_values("default", "libc++", "libstdc++")
    set_description("Select an alternate C++ standard library")
option_end()

option("fno-exceptions")
    set_default(false)
    set_showmenu(true)
    set_description("Disable C++ exceptions")
option_end()

option("warnings-as-errors")
    set_default(true)
    set_showmenu(true)
    set_description("Treat compiler warnings as errors")
option_end()
